<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {   
        // DB::table('users')->truncate();
        //seed registered students
        DB::table('users')->insert([
            [
                'name' => 'Bob',
                'email' => 'Bob@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00110',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Tom',
                'email' => 'Tom@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00111',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Jerry',
                'email' => 'Jerry@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00112',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Liam',
                'email' => 'Liam@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00113',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Asher',
                'email' => 'Asher@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00114',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Noah',
                'email' => 'Noah@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00115',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Mia',
                'email' => 'Mia@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00116',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Ava',
                'email' => 'Ava@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00117',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Emma',
                'email' => 'Emma@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00118',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Daniel',
                'email' => 'Daniel@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00119',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Mary',
                'email' => 'Mary@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00120',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Sarah',
                'email' => 'Sarah@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00121',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Linda',
                'email' => 'Linda@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00122',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Michael',
                'email' => 'Michael@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00123',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
            [
                'name' => 'Alice',
                'email' => 'Alice@example.com',
                'password' => bcrypt('123456'),
                's_number' => 's00124',
                't_number' => null,
                'user_type' => 'student',
                'avg_rate' => null,
                'is_registered' => true, 
            ],
        ]);
        //seed teachers, teachers don't need to register
        DB::table('users')->insert([
            [
                'name' => 'John',
                'email' => 'John@example.com',
                'password' => bcrypt('123456'),
                's_number' => null,
                't_number' => 't00110',
                'user_type' => 'teacher',
                'avg_rate' => null,
                'is_registered' => null, 
            ],
            [
                'name' => 'Kevin',
                'email' => 'Kevin@example.com',
                'password' => bcrypt('123456'),
                's_number' => null,
                't_number' => 't00111',
                'user_type' => 'teacher',
                'avg_rate' => null,
                'is_registered' => null, 
            ],
            [
                'name' => 'James',
                'email' => 'James@example.com',
                'password' => bcrypt('123456'),
                's_number' => null,
                't_number' => 't00112',
                'user_type' => 'teacher',
                'avg_rate' => null,
                'is_registered' => null, 
            ],
            [
                'name' => 'Andrew',
                'email' => 'Andrew@example.com',
                'password' => bcrypt('123456'),
                's_number' => null,
                't_number' => 't00113',
                'user_type' => 'teacher',
                'avg_rate' => null,
                'is_registered' => null, 
            ],
            [
                'name' => 'Herry',
                'email' => 'Herry@example.com',
                'password' => bcrypt('123456'),
                's_number' => null,
                't_number' => 't00114',
                'user_type' => 'teacher',
                'avg_rate' => null,
                'is_registered' => null, 
            ],
            [
                'name' => 'Percy',
                'email' => 'Percy@example.com',
                'password' => bcrypt('123456'),
                's_number' => null,
                't_number' => 't00115',
                'user_type' => 'teacher',
                'avg_rate' => null,
                'is_registered' => null, 
            ],
        ]);
    }
}
